### ISSUE TITLE
In workspaces view, wallpaper resizes to space between dock and panel

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/cosmic-workspaces-epoch#62]
If dock and/or panel aren't set to autohide, a copy of the wallpaper is resized into a space between them, while the actual wallpaper is visible under the dock/panel depending on their "stretch to screen edges" and transparency settings.

This happens with different orientations:

![screenshot-2024-07-11-20-37-54](https://github.com/user-attachments/assets/4b6869b0-8e5b-4030-a424-178e8dd4595d)

![screenshot-2024-07-11-20-39-02](https://github.com/user-attachments/assets/feaeacd8-15e1-4148-8ceb-0b03fc9c87f6)

**Comment by senntore** [comment]
This is fixed.

**Comment by Kartonrealista** [comment]
> This is fixed.

I just updated and logged out and no, it is not, and version on my system matches the latest commit hash.

![image](https://github.com/user-attachments/assets/87c73364-e2db-4d38-a630-d7e3880de682)

![screenshot-2024-07-18-07-04-49](https://github.com/user-attachments/assets/eeadc7c6-7ffe-43d3-bbda-2332a92929dd)

**Comment by senntore** [comment]
@Kartonrealista Are you on the development branch? If not, you'll have to wait for an update but don't worry this issue is fixed. Check the screenshot below with different wallpapers.
![screenshot-2024-07-18-07-40-42](https://github.com/user-attachments/assets/c6a55a71-5dfa-46fc-b2f9-5447406f6ffc)

![screenshot-2024-07-18-07-41-51](https://github.com/user-attachments/assets/db892241-fcfb-4c06-97b5-82ffc1f8228e)

![screenshot-2024-07-18-07-42-09](https://github.com/user-attachments/assets/57b5c57e-e92e-424c-99dd-58d0d86e5bb9)
